import * as esbuild from 'esbuild';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const DIST = 'dist';
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf-8'));
const APP_VERSION = pkg.version || 'DEV';
let COMMIT_HASH = 'DEV';
try { COMMIT_HASH = execSync('git rev-parse --short HEAD').toString().trim(); } catch {};

// Clean
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

// Build main process
await esbuild.build({
  entryPoints: ['src/main/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'cjs',
  outfile: `${DIST}/main.js`,
  external: ['electron'],
  define: {
    'MAIN_WINDOW_VITE_DEV_SERVER_URL': 'undefined',
    'MAIN_WINDOW_VITE_NAME': 'undefined',
    '__APP_VERSION__': JSON.stringify(APP_VERSION),
    '__COMMIT_HASH__': JSON.stringify(COMMIT_HASH),
  },
});

// Build preload
await esbuild.build({
  entryPoints: ['src/renderer/preload.ts'],
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'cjs',
  outfile: `${DIST}/preload.js`,
  external: ['electron'],
});

// Build preferences preload
await esbuild.build({
  entryPoints: ['src/renderer/preferences-preload.ts'],
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'cjs',
  outfile: `${DIST}/preferences-preload.js`,
  external: ['electron'],
});

// Build renderer JS
await esbuild.build({
  entryPoints: ['src/renderer/renderer.ts'],
  bundle: true,
  platform: 'browser',
  target: 'chrome120',
  format: 'iife',
  outfile: `${DIST}/renderer.js`,
});

// Build preferences renderer JS
await esbuild.build({
  entryPoints: ['src/renderer/preferences.ts'],
  bundle: true,
  platform: 'browser',
  target: 'chrome120',
  format: 'iife',
  outfile: `${DIST}/preferences.js`,
});

// Copy CSS files
const overlayCss = fs.readFileSync('src/renderer/styles/overlay.css', 'utf-8');
const toolbarCss = fs.readFileSync('src/renderer/styles/toolbar.css', 'utf-8');
const prefsCss = fs.readFileSync('src/renderer/styles/preferences.css', 'utf-8');

// Generate index.html with inlined CSS
const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Screen Paint0r</title>
  <style>${overlayCss}\n${toolbarCss}</style>
</head>
<body>
  <div id="app"></div>
  <script src="./renderer.js"></script>
</body>
</html>`;

fs.writeFileSync(`${DIST}/index.html`, html);

// Generate preferences.html
const prefsHtml = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Preferences</title>
  <style>${prefsCss}</style>
</head>
<body>
  <h1>Keybindings</h1>
  <p class="subtitle">Click a shortcut to change it, then press your new key combination.</p>
  <div id="bindings" class="bindings"></div>
  <div class="actions">
    <button id="save" class="primary">Save</button>
    <button id="reset" class="secondary">Reset to Defaults</button>
    <span id="status" class="status"></span>
  </div>
  <script src="./preferences.js"></script>
</body>
</html>`;

fs.writeFileSync(`${DIST}/preferences.html`, prefsHtml);

// Copy tray icon if available (generated by npm run icons)
if (fs.existsSync('assets/icon.png')) {
  fs.copyFileSync('assets/icon.png', `${DIST}/tray-icon.png`);
}

// Compile native click monitor (macOS only)
if (process.platform === 'darwin') {
  try {
    execSync(`swiftc -O -o ${DIST}/click-monitor src/native/click-monitor.swift -framework Cocoa`, { stdio: 'inherit' });
    console.log('Compiled click-monitor');
  } catch (e) {
    console.warn('Warning: Failed to compile click-monitor (pointer ping will not work)');
  }
}

console.log('Build complete → dist/');
